//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientBaseControlWebApp.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ClientBaseControlWebApp.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accounting.
        /// </summary>
        public static string AccountingNav {
            get {
                return ResourceManager.GetString("AccountingNav", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add this material to a procedure.
        /// </summary>
        public static string AddMaterialToProcedure {
            get {
                return ResourceManager.GetString("AddMaterialToProcedure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a new client.
        /// </summary>
        public static string AddNewClient {
            get {
                return ResourceManager.GetString("AddNewClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a new material.
        /// </summary>
        public static string AddNewMaterial {
            get {
                return ResourceManager.GetString("AddNewMaterial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a new procedure record.
        /// </summary>
        public static string AddProcedureRecord {
            get {
                return ResourceManager.GetString("AddProcedureRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a new procedure type.
        /// </summary>
        public static string AddProcedureType {
            get {
                return ResourceManager.GetString("AddProcedureType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allergy.
        /// </summary>
        public static string Allergy {
            get {
                return ResourceManager.GetString("Allergy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        public static string AmountLabel {
            get {
                return ResourceManager.GetString("AmountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appearance.
        /// </summary>
        public static string Appearance {
            get {
                return ResourceManager.GetString("Appearance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Black.
        /// </summary>
        public static string BlackHairColor {
            get {
                return ResourceManager.GetString("BlackHairColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blonde.
        /// </summary>
        public static string BlondeHairColor {
            get {
                return ResourceManager.GetString("BlondeHairColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blue.
        /// </summary>
        public static string BlueColor {
            get {
                return ResourceManager.GetString("BlueColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brown.
        /// </summary>
        public static string BrownColor {
            get {
                return ResourceManager.GetString("BrownColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brown.
        /// </summary>
        public static string BrownHairColor {
            get {
                return ResourceManager.GetString("BrownHairColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CancelButton {
            get {
                return ResourceManager.GetString("CancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capillaries.
        /// </summary>
        public static string Capillaries {
            get {
                return ResourceManager.GetString("Capillaries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client.
        /// </summary>
        public static string ChooseClientLabel {
            get {
                return ResourceManager.GetString("ChooseClientLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a material.
        /// </summary>
        public static string ChooseMaterial {
            get {
                return ResourceManager.GetString("ChooseMaterial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose.
        /// </summary>
        public static string ChooseSelection {
            get {
                return ResourceManager.GetString("ChooseSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Circles under the eyes color.
        /// </summary>
        public static string CirclesUnderEyesColor {
            get {
                return ResourceManager.GetString("CirclesUnderEyesColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allergies.
        /// </summary>
        public static string ClientAllergiesLabel {
            get {
                return ResourceManager.GetString("ClientAllergiesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birthday.
        /// </summary>
        public static string ClientBirthdayLabel {
            get {
                return ResourceManager.GetString("ClientBirthdayLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to delete this client?.
        /// </summary>
        public static string ClientDeleteConfirmation {
            get {
                return ResourceManager.GetString("ClientDeleteConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string ClientEmailLabel {
            get {
                return ResourceManager.GetString("ClientEmailLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indication color.
        /// </summary>
        public static string ClientIndicationColorLabel {
            get {
                return ResourceManager.GetString("ClientIndicationColorLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initial note.
        /// </summary>
        public static string ClientInitialNoteLabel {
            get {
                return ResourceManager.GetString("ClientInitialNoteLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main note.
        /// </summary>
        public static string ClientMainNoteLabel {
            get {
                return ResourceManager.GetString("ClientMainNoteLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string ClientNameLabel {
            get {
                return ResourceManager.GetString("ClientNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of procedures.
        /// </summary>
        public static string ClientNumberOfProceduresLabel {
            get {
                return ResourceManager.GetString("ClientNumberOfProceduresLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number.
        /// </summary>
        public static string ClientPhoneNumberLabel {
            get {
                return ResourceManager.GetString("ClientPhoneNumberLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clients.
        /// </summary>
        public static string ClientsNav {
            get {
                return ResourceManager.GetString("ClientsNav", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surname.
        /// </summary>
        public static string ClientSurnameLabel {
            get {
                return ResourceManager.GetString("ClientSurnameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cold pink.
        /// </summary>
        public static string ColdPinkShade {
            get {
                return ResourceManager.GetString("ColdPinkShade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note.
        /// </summary>
        public static string CommentLabel {
            get {
                return ResourceManager.GetString("CommentLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration.
        /// </summary>
        public static string ConfigurationNav {
            get {
                return ResourceManager.GetString("ConfigurationNav", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string DateLabel {
            get {
                return ResourceManager.GetString("DateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string DeleteButton {
            get {
                return ResourceManager.GetString("DeleteButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string DescriptionLabel {
            get {
                return ResourceManager.GetString("DescriptionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string DetailsButton {
            get {
                return ResourceManager.GetString("DetailsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documents.
        /// </summary>
        public static string DocumentsNav {
            get {
                return ResourceManager.GetString("DocumentsNav", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Does`t have.
        /// </summary>
        public static string DoesNotHave {
            get {
                return ResourceManager.GetString("DoesNotHave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dry skin.
        /// </summary>
        public static string DrySkin {
            get {
                return ResourceManager.GetString("DrySkin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string EditButton {
            get {
                return ResourceManager.GetString("EditButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit client data.
        /// </summary>
        public static string EditClient {
            get {
                return ResourceManager.GetString("EditClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit the material.
        /// </summary>
        public static string EditMaterial {
            get {
                return ResourceManager.GetString("EditMaterial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employees.
        /// </summary>
        public static string EmployeesNav {
            get {
                return ResourceManager.GetString("EmployeesNav", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eye color.
        /// </summary>
        public static string EyeColor {
            get {
                return ResourceManager.GetString("EyeColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fat skin.
        /// </summary>
        public static string FatSkin {
            get {
                return ResourceManager.GetString("FatSkin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This field is required.
        /// </summary>
        public static string FieldIsRequired {
            get {
                return ResourceManager.GetString("FieldIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to for.
        /// </summary>
        public static string For {
            get {
                return ResourceManager.GetString("For", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ginger.
        /// </summary>
        public static string GingerHairColor {
            get {
                return ResourceManager.GetString("GingerHairColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gray.
        /// </summary>
        public static string GrayColor {
            get {
                return ResourceManager.GetString("GrayColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gray.
        /// </summary>
        public static string GrayHairColor {
            get {
                return ResourceManager.GetString("GrayHairColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Green.
        /// </summary>
        public static string GreenColor {
            get {
                return ResourceManager.GetString("GreenColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hair color.
        /// </summary>
        public static string HairColor {
            get {
                return ResourceManager.GetString("HairColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has.
        /// </summary>
        public static string Has {
            get {
                return ResourceManager.GetString("Has", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has allergy?.
        /// </summary>
        public static string HasAllergyLabel {
            get {
                return ResourceManager.GetString("HasAllergyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client has allergy!.
        /// </summary>
        public static string HasAllergyWarning {
            get {
                return ResourceManager.GetString("HasAllergyWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capillaries.
        /// </summary>
        public static string HasCapillaries {
            get {
                return ResourceManager.GetString("HasCapillaries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tan.
        /// </summary>
        public static string HasTan {
            get {
                return ResourceManager.GetString("HasTan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light blue.
        /// </summary>
        public static string LightBlueColor {
            get {
                return ResourceManager.GetString("LightBlueColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light brown.
        /// </summary>
        public static string LightBrownHairColor {
            get {
                return ResourceManager.GetString("LightBrownHairColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light green.
        /// </summary>
        public static string LightGreenColor {
            get {
                return ResourceManager.GetString("LightGreenColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string LoginNav {
            get {
                return ResourceManager.GetString("LoginNav", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please log in to continue.
        /// </summary>
        public static string LoginRequest {
            get {
                return ResourceManager.GetString("LoginRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string LogoutNav {
            get {
                return ResourceManager.GetString("LogoutNav", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This material has already been added to the procudeure.
        /// </summary>
        public static string MaterialAlreadyAdded {
            get {
                return ResourceManager.GetString("MaterialAlreadyAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to delete this material?.
        /// </summary>
        public static string MaterialDeleteConfirmation {
            get {
                return ResourceManager.GetString("MaterialDeleteConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Needle.
        /// </summary>
        public static string MaterialNeedle {
            get {
                return ResourceManager.GetString("MaterialNeedle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string MaterialOther {
            get {
                return ResourceManager.GetString("MaterialOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pigment.
        /// </summary>
        public static string MaterialPigment {
            get {
                return ResourceManager.GetString("MaterialPigment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Materials.
        /// </summary>
        public static string MaterialsNav {
            get {
                return ResourceManager.GetString("MaterialsNav", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Material type.
        /// </summary>
        public static string MaterialTypeLabel {
            get {
                return ResourceManager.GetString("MaterialTypeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Membrane color.
        /// </summary>
        public static string MembraneColor {
            get {
                return ResourceManager.GetString("MembraneColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mg.
        /// </summary>
        public static string MgUnit {
            get {
                return ResourceManager.GetString("MgUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ml.
        /// </summary>
        public static string MlUnit {
            get {
                return ResourceManager.GetString("MlUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string NameLabel {
            get {
                return ResourceManager.GetString("NameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Needle type.
        /// </summary>
        public static string NeedleType {
            get {
                return ResourceManager.GetString("NeedleType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allergies were not mentioned.
        /// </summary>
        public static string NoAllergy {
            get {
                return ResourceManager.GetString("NoAllergy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal skin.
        /// </summary>
        public static string NormalSkin {
            get {
                return ResourceManager.GetString("NormalSkin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not chosen.
        /// </summary>
        public static string NotChosen {
            get {
                return ResourceManager.GetString("NotChosen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note.
        /// </summary>
        public static string NoteLabel {
            get {
                return ResourceManager.GetString("NoteLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pcs.
        /// </summary>
        public static string PiecesUnit {
            get {
                return ResourceManager.GetString("PiecesUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procedure records.
        /// </summary>
        public static string ProcedureRecordsNav {
            get {
                return ResourceManager.GetString("ProcedureRecordsNav", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procedures.
        /// </summary>
        public static string ProceduresNav {
            get {
                return ResourceManager.GetString("ProceduresNav", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to delete this procedure type?.
        /// </summary>
        public static string ProcedureTypeDeleteConfirmation {
            get {
                return ResourceManager.GetString("ProcedureTypeDeleteConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProcedureType.
        /// </summary>
        public static string ProcedureTypeLabel {
            get {
                return ResourceManager.GetString("ProcedureTypeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procedure types.
        /// </summary>
        public static string ProcedureTypesNav {
            get {
                return ResourceManager.GetString("ProcedureTypesNav", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red.
        /// </summary>
        public static string RedColor {
            get {
                return ResourceManager.GetString("RedColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string RegisterNav {
            get {
                return ResourceManager.GetString("RegisterNav", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string ResetButton {
            get {
                return ResourceManager.GetString("ResetButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return.
        /// </summary>
        public static string ReturnBack {
            get {
                return ResourceManager.GetString("ReturnBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string SaveButton {
            get {
                return ResourceManager.GetString("SaveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string SearchBar {
            get {
                return ResourceManager.GetString("SearchBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected materials.
        /// </summary>
        public static string SelectedMaterials {
            get {
                return ResourceManager.GetString("SelectedMaterials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show all.
        /// </summary>
        public static string ShowAllButton {
            get {
                return ResourceManager.GetString("ShowAllButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skin type.
        /// </summary>
        public static string SkinType {
            get {
                return ResourceManager.GetString("SkinType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tan.
        /// </summary>
        public static string Tan {
            get {
                return ResourceManager.GetString("Tan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit of measurement.
        /// </summary>
        public static string UnitsOfMeasurementLabel {
            get {
                return ResourceManager.GetString("UnitsOfMeasurementLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warm pink.
        /// </summary>
        public static string WarmPinkShade {
            get {
                return ResourceManager.GetString("WarmPinkShade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yellow.
        /// </summary>
        public static string YellowColor {
            get {
                return ResourceManager.GetString("YellowColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
